"""empty message

Revision ID: 1c276133e027
Revises: 546b8fcfbda4
Create Date: 2023-04-11 15:33:37.649802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c276133e027'
down_revision = '546b8fcfbda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_title')
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.create_index('ix_movie_title', ['title'], unique=False)

    # ### end Alembic commands ###
